from __future__ import annotations

"""
==========================================================
SOTP LONG-TERM EQUITY DOMAIN CONSTANTS
Stage   : Shared / Pipeline-Wide
Version : V1.1 (Complete Taxonomy)
==========================================================

Authoritative vocabulary and defaults used across the entire
Long-Term Equity SOTP valuation pipeline.

This module contains:
• Pipeline metadata & stage IDs
• Base pipeline status values
• Relationship & segment taxonomies
• Economic interpretation & classification taxonomies
• Stage-specific status taxonomies (Classification, Valuation, SOTP)
• Valuation methods
• Parent capital structure defaults
• Reporting & numeric defaults
• Investment recommendation types
• Confidence & importance levels
"""

# ==========================================================
# PIPELINE METADATA
# ==========================================================

PIPELINE_VERSION = "1.0"
EXPECTED_ENTITY_COUNT = 58


# ==========================================================
# STAGE IDS
# ==========================================================

STAGE_13A = "13A"
STAGE_13B = "13B"
STAGE_13C_1 = "13C.1"
STAGE_13C_2 = "13C.2"
STAGE_13C_3 = "13C.3"
STAGE_13D = "13D"
STAGE_14 = "14"
STAGE_15 = "15"
STAGE_16 = "16"


# ==========================================================
# BASE PIPELINE STATUS
# ==========================================================

STATUS_OK = "OK"
STATUS_UNAVAILABLE = "UNAVAILABLE"
STATUS_UNRESOLVED = "UNRESOLVED"
STATUS_RESOLVED = "RESOLVED"

PIPELINE_STATUSES = {
    STATUS_OK,
    STATUS_UNAVAILABLE,
    STATUS_UNRESOLVED,
    STATUS_RESOLVED,
}


# ==========================================================
# REPORTING DEFAULTS
# ==========================================================

DEFAULT_CURRENCY = "INR"
DEFAULT_REPORTING_UNIT = "Million"
DEFAULT_TIMEZONE = "UTC"


# ==========================================================
# NUMERIC DEFAULTS
# ==========================================================

DEFAULT_NUMERIC_VALUE = 0.0
DEFAULT_PERCENTAGE = 0.0
DEFAULT_NULL_TEXT = "N/A"


# ==========================================================
# RELATIONSHIPS
# ==========================================================

RELATIONSHIP_ASSOCIATE = "ASSOCIATE"
RELATIONSHIP_JOINT_VENTURE = "JOINT_VENTURE"
RELATIONSHIP_SUBSIDIARY = "SUBSIDIARY"
RELATIONSHIP_CONTROLLED_ENTITY = "CONTROLLED_ENTITY"

RELATIONSHIP_TYPES = {
    RELATIONSHIP_ASSOCIATE,
    RELATIONSHIP_JOINT_VENTURE,
    RELATIONSHIP_SUBSIDIARY,
    RELATIONSHIP_CONTROLLED_ENTITY,
}


# ==========================================================
# OPERATING SEGMENTS
# ==========================================================

SEGMENT_RETAIL = "RETAIL"
SEGMENT_DIGITAL_SERVICES = "DIGITAL_SERVICES"
SEGMENT_OIL_TO_CHEMICALS = "OIL_TO_CHEMICALS"
SEGMENT_OIL_AND_GAS = "OIL_AND_GAS"
SEGMENT_NEW_ENERGY = "NEW_ENERGY"
SEGMENT_FINANCIAL_SERVICES = "FINANCIAL_SERVICES"
SEGMENT_OTHER = "OTHER"

OPERATING_SEGMENTS = {
    SEGMENT_RETAIL,
    SEGMENT_DIGITAL_SERVICES,
    SEGMENT_OIL_TO_CHEMICALS,
    SEGMENT_OIL_AND_GAS,
    SEGMENT_NEW_ENERGY,
    SEGMENT_FINANCIAL_SERVICES,
    SEGMENT_OTHER,
}


# ==========================================================
# INTERPRETATION TYPES
# ==========================================================

INTERPRETATION_OPERATING_ENTITY = "OPERATING_ENTITY"
INTERPRETATION_OPERATING_INFRASTRUCTURE = "OPERATING_INFRASTRUCTURE"
INTERPRETATION_STRATEGIC_INVESTMENT = "STRATEGIC_INVESTMENT"
INTERPRETATION_FINANCIAL_INVESTMENT = "FINANCIAL_INVESTMENT"
INTERPRETATION_INCUBATION_INVESTMENT = "INCUBATION_INVESTMENT"
INTERPRETATION_PASSIVE_INVESTMENT = "PASSIVE_INVESTMENT"
INTERPRETATION_NON_OPERATING_ASSET = "NON_OPERATING_ASSET"
INTERPRETATION_ELIMINATED_ENTITY = "ELIMINATED_ENTITY"
INTERPRETATION_UNRESOLVED = STATUS_UNRESOLVED

INTERPRETATION_TYPES = {
    INTERPRETATION_OPERATING_ENTITY,
    INTERPRETATION_OPERATING_INFRASTRUCTURE,
    INTERPRETATION_STRATEGIC_INVESTMENT,
    INTERPRETATION_FINANCIAL_INVESTMENT,
    INTERPRETATION_INCUBATION_INVESTMENT,
    INTERPRETATION_PASSIVE_INVESTMENT,
    INTERPRETATION_NON_OPERATING_ASSET,
    INTERPRETATION_ELIMINATED_ENTITY,
    INTERPRETATION_UNRESOLVED,
}


# ==========================================================
# CLASSIFICATION TYPES
# ==========================================================

CLASSIFICATION_OPERATING_SUBSIDIARY = "OPERATING_SUBSIDIARY"
CLASSIFICATION_OPERATING_ASSOCIATE = "OPERATING_ASSOCIATE"
CLASSIFICATION_OPERATING_JOINT_VENTURE = "OPERATING_JOINT_VENTURE"
CLASSIFICATION_OPERATING_INFRASTRUCTURE = "OPERATING_INFRASTRUCTURE"

CLASSIFICATION_STRATEGIC_INVESTMENT = "STRATEGIC_INVESTMENT"
CLASSIFICATION_FINANCIAL_INVESTMENT = "FINANCIAL_INVESTMENT"
CLASSIFICATION_INCUBATION_INVESTMENT = "INCUBATION_INVESTMENT"
CLASSIFICATION_PASSIVE_INVESTMENT = "PASSIVE_INVESTMENT"

CLASSIFICATION_NON_OPERATING_ASSET = "NON_OPERATING_ASSET"
CLASSIFICATION_ELIMINATE = "ELIMINATE"
CLASSIFICATION_UNRESOLVED = STATUS_UNRESOLVED

CLASSIFICATION_TYPES = {
    CLASSIFICATION_OPERATING_SUBSIDIARY,
    CLASSIFICATION_OPERATING_ASSOCIATE,
    CLASSIFICATION_OPERATING_JOINT_VENTURE,
    CLASSIFICATION_OPERATING_INFRASTRUCTURE,
    CLASSIFICATION_STRATEGIC_INVESTMENT,
    CLASSIFICATION_FINANCIAL_INVESTMENT,
    CLASSIFICATION_INCUBATION_INVESTMENT,
    CLASSIFICATION_PASSIVE_INVESTMENT,
    CLASSIFICATION_NON_OPERATING_ASSET,
    CLASSIFICATION_ELIMINATE,
    CLASSIFICATION_UNRESOLVED,
}


# ==========================================================
# STAGE-SPECIFIC STATUS TAXONOMIES
# ==========================================================

# Classification Statuses (Stage 13C)
CLASSIFICATION_STATUS_COMPLETE = "COMPLETE"
CLASSIFICATION_STATUS_PARTIAL = "PARTIAL"
CLASSIFICATION_STATUS_UNRESOLVED = STATUS_UNRESOLVED
CLASSIFICATION_STATUS_CONFLICTING = "CONFLICTING"

CLASSIFICATION_STATUSES = {
    CLASSIFICATION_STATUS_COMPLETE,
    CLASSIFICATION_STATUS_PARTIAL,
    CLASSIFICATION_STATUS_UNRESOLVED,
    CLASSIFICATION_STATUS_CONFLICTING,
}

# Valuation Statuses (Stage 13D)
VALUATION_STATUS_COMPLETE = "COMPLETE"
VALUATION_STATUS_PENDING_MODEL = "PENDING_MODEL"
VALUATION_STATUS_UNAUTHORIZED = "UNAUTHORIZED"
VALUATION_STATUS_EXCLUDED = "EXCLUDED"
VALUATION_STATUS_FAILED = "FAILED"

VALUATION_STATUSES = {
    VALUATION_STATUS_COMPLETE,
    VALUATION_STATUS_PENDING_MODEL,
    VALUATION_STATUS_UNAUTHORIZED,
    VALUATION_STATUS_EXCLUDED,
    VALUATION_STATUS_FAILED,
}

# SOTP Aggregation Statuses (Stage 14)
SOTP_STATUS_COMPLETE = "COMPLETE"
SOTP_STATUS_PARTIAL = "PARTIAL"
SOTP_STATUS_FAILED = "FAILED"

SOTP_STATUSES = {
    SOTP_STATUS_COMPLETE,
    SOTP_STATUS_PARTIAL,
    SOTP_STATUS_FAILED,
}


# ==========================================================
# VALUATION METHODS
# ==========================================================

VALUATION_METHOD_DCF = "DCF"
VALUATION_METHOD_MARKET_VALUE = "MARKET_VALUE"
VALUATION_METHOD_FAIR_VALUE = "FAIR_VALUE"
VALUATION_METHOD_BOOK_VALUE = "BOOK_VALUE"
VALUATION_METHOD_COST = "COST"
VALUATION_METHOD_NONE = "NONE"

VALUATION_METHODS = {
    VALUATION_METHOD_DCF,
    VALUATION_METHOD_MARKET_VALUE,
    VALUATION_METHOD_FAIR_VALUE,
    VALUATION_METHOD_BOOK_VALUE,
    VALUATION_METHOD_COST,
    VALUATION_METHOD_NONE,
}


# ==========================================================
# PARENT CAPITAL STRUCTURE & SOTP DEFAULTS
# ==========================================================

DEFAULT_PARENT_SHARES_OUTSTANDING_MN = 6765.0
DEFAULT_CONGLOMERATE_DISCOUNT_PCT = 0.15


# ==========================================================
# RECOMMENDATION TYPES (Stage 15 & 16)
# ==========================================================

RECOMMENDATION_STRONG_BUY = "STRONG_BUY"
RECOMMENDATION_BUY = "BUY"
RECOMMENDATION_HOLD = "HOLD"
RECOMMENDATION_SELL = "SELL"
RECOMMENDATION_STRONG_SELL = "STRONG_SELL"

RECOMMENDATION_TYPES = {
    RECOMMENDATION_STRONG_BUY,
    RECOMMENDATION_BUY,
    RECOMMENDATION_HOLD,
    RECOMMENDATION_SELL,
    RECOMMENDATION_STRONG_SELL,
}


# ==========================================================
# CONFIDENCE & IMPORTANCE
# ==========================================================

CONFIDENCE_HIGH = "HIGH"
CONFIDENCE_MEDIUM = "MEDIUM"
CONFIDENCE_LOW = "LOW"

CONFIDENCE_LEVELS = {
    CONFIDENCE_HIGH,
    CONFIDENCE_MEDIUM,
    CONFIDENCE_LOW,
}

IMPORTANCE_HIGH = "HIGH"
IMPORTANCE_MEDIUM = "MEDIUM"
IMPORTANCE_LOW = "LOW"

IMPORTANCE_LEVELS = {
    IMPORTANCE_HIGH,
    IMPORTANCE_MEDIUM,
    IMPORTANCE_LOW,
}
