from __future__ import annotations

import html
import logging
import os
from collections.abc import Mapping
from typing import Any

from services.report.models import ReportResult

logger = logging.getLogger(__name__)


class ProductionReportEngine:
    """Generate reports from supplied analysis data without fabricating values."""

    @staticmethod
    def _value(data: Mapping[str, Any], key: str) -> Any:
        value = data.get(key)
        return "UNAVAILABLE" if value is None else value

    @staticmethod
    def _format_value(value: Any, prefix: str = "Rs.") -> str:
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            return f"{prefix}{value:,.2f}"
        return str(value)

    def generate(
        self,
        symbol: str,
        format_type: str = "MULTI-FORMAT",
        analysis_data: dict[str, Any] | None = None,
    ) -> ReportResult:
        """Create a report and explicitly mark missing upstream values."""
        normalized_symbol = symbol.strip() if isinstance(symbol, str) else ""
        if not normalized_symbol:
            raise ValueError("symbol must be a non-empty string")

        data = analysis_data or {}
        recommendation = self._value(data, "recommendation")
        blended_fair_value = self._value(data, "blended_fair_value")
        composite_score = self._value(data, "composite_score")
        dcf_ev = self._value(data, "dcf_ev")
        relative_blend = self._value(data, "relative_blend")
        sotp_equity = self._value(data, "sotp_equity")
        input_complete = bool(data) and all(
            key in data and data[key] is not None
            for key in (
                "recommendation",
                "blended_fair_value",
                "composite_score",
            )
        )

        safe_symbol = html.escape(normalized_symbol)
        markdown_content = f"""# Institutional Equity Research Report: {normalized_symbol}
## Executive Summary
Comprehensive AI-driven valuation, fundamental analysis, and portfolio positioning report.

- **Symbol**: {normalized_symbol}
- **Recommendation**: {recommendation}
- **Blended Fair Value**: {self._format_value(blended_fair_value)}
- **Composite AI Score**: {f'{composite_score} / 100' if isinstance(composite_score, (int, float)) and not isinstance(composite_score, bool) else composite_score}

## Valuation Breakdown
- **DCF Enterprise Value**: {self._format_value(dcf_ev)}
- **Relative Valuation Blend**: {self._format_value(relative_blend)}
- **SOTP Conglomerate Equity Value**: {self._format_value(sotp_equity)}

---
*Generated by EROS Institutional Research Platform.*
"""

        html_content = f"""<html>
<head><title>Research Report - {safe_symbol}</title></head>
<body style="font-family: Arial, sans-serif; padding: 20px;">
    <h1>Institutional Equity Research Report: {safe_symbol}</h1>
    <h2>Executive Summary</h2>
    <p><b>Recommendation:</b> {html.escape(str(recommendation))}</p>
    <p><b>Blended Fair Value:</b> {html.escape(self._format_value(blended_fair_value))}</p>
    <p><b>Composite AI Score:</b> {html.escape(str(composite_score))}</p>
    <hr/>
    <p><i>Generated by EROS Institutional Research Platform.</i></p>
</body>
</html>"""

        output_dir = "reports_output"
        os.makedirs(output_dir, exist_ok=True)
        file_path = os.path.join(output_dir, f"{normalized_symbol}_report.html")
        with open(file_path, "w", encoding="utf-8") as report_file:
            report_file.write(html_content)

        return ReportResult(
            symbol=normalized_symbol,
            format_type=format_type,
            file_path=file_path,
            content=markdown_content,
            metadata={
                "status": "generated",
                "formats": ["HTML", "MARKDOWN", "JSON"],
                "input_complete": input_complete,
            },
        )


class ReportEngine(ProductionReportEngine):
    """Backward-compatible alias used by existing pipeline integrations."""
