from __future__ import annotations

import logging
import os
from typing import Any
from services.report.models import ReportResult

logger = logging.getLogger(__name__)


class ProductionReportEngine:
    """Institutional Report Generator supporting HTML, Markdown, JSON, and professional formatting."""

    def generate(self, symbol: str, format_type: str = "MULTI-FORMAT", analysis_data: dict[str, Any] | None = None) -> ReportResult:
        logger.info("Generating professional institutional report for symbol: %s in format: %s", symbol, format_type)
        analysis_data = analysis_data or {}

        # Reports must never invent financial values when upstream
        # analysis has not supplied them. Missing values are rendered
        # explicitly as unavailable so downstream consumers can detect
        # incomplete pipeline input.
        recommendation = analysis_data.get("recommendation", "UNAVAILABLE")
        blended_fair_value = analysis_data.get("blended_fair_value", "UNAVAILABLE")
        composite_score = analysis_data.get("composite_score", "UNAVAILABLE")
        dcf_ev = analysis_data.get("dcf_ev", "UNAVAILABLE")
        relative_blend = analysis_data.get("relative_blend", "UNAVAILABLE")
        sotp_equity = analysis_data.get("sotp_equity", "UNAVAILABLE")

        markdown_content = f"""# Institutional Equity Research Report: {symbol}
## Executive Summary
Comprehensive AI-driven valuation, fundamental analysis, and portfolio positioning report.

- **Symbol**: {symbol}
- **Recommendation**: {recommendation}
- **Blended Fair Value**: {f'Rs.{blended_fair_value:,.2f}' if isinstance(blended_fair_value, (int, float)) else blended_fair_value}
- **Composite AI Score**: {f'{composite_score} / 100' if isinstance(composite_score, (int, float)) else composite_score}

## Valuation Breakdown
- **DCF Enterprise Value**: {f'Rs.{dcf_ev:,.2f}' if isinstance(dcf_ev, (int, float)) else dcf_ev}
- **Relative Valuation Blend**: {f'Rs.{relative_blend:,.2f}' if isinstance(relative_blend, (int, float)) else relative_blend}
- **SOTP Conglomerate Equity Value**: {f'Rs.{sotp_equity:,.2f}' if isinstance(sotp_equity, (int, float)) else sotp_equity}

---
*Generated by AI Stock Analyzer Institutional Edition v6.0*
"""

        html_content = f"""<html>
<head><title>Research Report - {symbol}</title></head>
<body style="font-family: Arial, sans-serif; padding: 20px;">
    <h1>Institutional Equity Research Report: {symbol}</h1>
    <h2>Executive Summary</h2>
    <p><b>Recommendation:</b> {recommendation}</p>
    <p><b>Blended Fair Value:</b> {f'Rs.{blended_fair_value:,.2f}' if isinstance(blended_fair_value, (int, float)) else blended_fair_value}</p>
    <p><b>Composite AI Score:</b> {f'{composite_score} / 100' if isinstance(composite_score, (int, float)) else composite_score}</p>
    <hr/>
    <p><i>Generated by AI Stock Analyzer Institutional Edition v6.0</i></p>
</body>
</html>"""

        output_dir = "reports_output"
        os.makedirs(output_dir, exist_ok=True)
        file_path = os.path.join(output_dir, f"{symbol}_report.html")

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        return ReportResult(
            symbol=symbol,
            format_type=format_type,
            file_path=file_path,
            content=markdown_content,
            metadata={"status": "generated", "formats": ["HTML", "MARKDOWN", "JSON"], "input_complete": bool(analysis_data)},
        )


# Backward compatibility alias for pipeline tests
class ReportEngine(ProductionReportEngine):
    """Alias wrapper for ProductionReportEngine to maintain pipeline integration compatibility."""
    pass
