"""Shared broad sector labels for dashboard presentation metadata."""

SECTOR_BY_SYMBOL = {
    "RELIANCE": "Energy",
    "ONGC": "Energy",
    "BPCL": "Energy",
    "IOC": "Energy",
    "GAIL": "Energy",
    "TCS": "IT",
    "INFY": "IT",
    "HCLTECH": "IT",
    "WIPRO": "IT",
    "TECHM": "IT",
    "HDFCBANK": "Financials",
    "ICICIBANK": "Financials",
    "SBIN": "Financials",
    "KOTAKBANK": "Financials",
    "AXISBANK": "Financials",
    "BAJFINANCE": "Financials",
    "BAJAJFINSV": "Financials",
    "INDUSINDBK": "Financials",
    "BANKBARODA": "Financials",
    "CANBK": "Financials",
    "IDFCFIRSTB": "Financials",
    "PNB": "Financials",
    "LT": "Industrials",
    "BEL": "Industrials",
    "HAL": "Industrials",
    "ADANIENT": "Industrials",
    "ADANIPORTS": "Industrials",
    "IRFC": "Industrials",
    "RVNL": "Industrials",
    "ITC": "Consumer",
    "HINDUNILVR": "Consumer",
    "NESTLEIND": "Consumer",
    "BRITANNIA": "Consumer",
    "TATACONSUM": "Consumer",
    "TITAN": "Consumer",
    "MARUTI": "Automobiles",
    "M&M": "Automobiles",
    "TATAMOTORS": "Automobiles",
    "EICHERMOT": "Automobiles",
    "HEROMOTOCO": "Automobiles",
    "BAJAJ-AUTO": "Automobiles",
    "SUNPHARMA": "Pharma",
    "CIPLA": "Pharma",
    "DRREDDY": "Pharma",
    "DIVISLAB": "Pharma",
    "APOLLOHOSP": "Healthcare",
    "ULTRACEMCO": "Cement",
    "GRASIM": "Diversified",
    "HINDALCO": "Metals",
    "TATASTEEL": "Metals",
    "JSWSTEEL": "Metals",
    "COALINDIA": "Mining",
    "NTPC": "Utilities",
    "POWERGRID": "Utilities",
    "ASIANPAINT": "Materials",
    "BHARTIARTL": "Telecom",
    "INDIGO": "Airlines",
    "ZOMATO": "Internet",
    "PAYTM": "Financial Technology",
    "JIOFIN": "Financials",
}


def sector_for_symbol(symbol: str) -> str:
    """Return a broad sector label without inventing an unmapped classification."""
    return SECTOR_BY_SYMBOL.get(str(symbol).strip().upper(), "Unclassified")
