"""
==========================================================
LONG-TERM EQUITY DOMAIN CONSTANTS
Stage   : 13C.3 Constants Update
Version : V1.0
==========================================================

Domain constants for SOTP classification engine including:
- Classification Taxonomy
- Valuation Method Taxonomy
- Classification Status Taxonomy
"""

# Base Status Constants
STATUS_UNRESOLVED = "UNRESOLVED"
EXPECTED_ENTITY_COUNT = 58

# Relationship Constants
RELATIONSHIP_SUBSIDIARY = "SUBSIDIARY"
RELATIONSHIP_ASSOCIATE = "ASSOCIATE"
RELATIONSHIP_JOINT_VENTURE = "JOINT_VENTURE"
RELATIONSHIP_INVESTMENT = "INVESTMENT"

# ==========================================================
# 1. Classification Taxonomy
# ==========================================================
CLASSIFICATION_OPERATING_SUBSIDIARY = "OPERATING_SUBSIDIARY"
CLASSIFICATION_OPERATING_ASSOCIATE = "OPERATING_ASSOCIATE"
CLASSIFICATION_OPERATING_JOINT_VENTURE = "OPERATING_JOINT_VENTURE"
CLASSIFICATION_OPERATING_INFRASTRUCTURE = "OPERATING_INFRASTRUCTURE"

CLASSIFICATION_STRATEGIC_INVESTMENT = "STRATEGIC_INVESTMENT"
CLASSIFICATION_FINANCIAL_INVESTMENT = "FINANCIAL_INVESTMENT"
CLASSIFICATION_INCUBATION_INVESTMENT = "INCUBATION_INVESTMENT"
CLASSIFICATION_PASSIVE_INVESTMENT = "PASSIVE_INVESTMENT"

CLASSIFICATION_NON_OPERATING_ASSET = "NON_OPERATING_ASSET"
CLASSIFICATION_ELIMINATE = "ELIMINATE"
CLASSIFICATION_UNRESOLVED = STATUS_UNRESOLVED

CLASSIFICATION_TYPES = {
    CLASSIFICATION_OPERATING_SUBSIDIARY,
    CLASSIFICATION_OPERATING_ASSOCIATE,
    CLASSIFICATION_OPERATING_JOINT_VENTURE,
    CLASSIFICATION_OPERATING_INFRASTRUCTURE,
    CLASSIFICATION_STRATEGIC_INVESTMENT,
    CLASSIFICATION_FINANCIAL_INVESTMENT,
    CLASSIFICATION_INCUBATION_INVESTMENT,
    CLASSIFICATION_PASSIVE_INVESTMENT,
    CLASSIFICATION_NON_OPERATING_ASSET,
    CLASSIFICATION_ELIMINATE,
    CLASSIFICATION_UNRESOLVED,
}

# ==========================================================
# 2. Valuation Method Taxonomy
# ==========================================================
VALUATION_METHOD_DCF = "DCF"
VALUATION_METHOD_MARKET_VALUE = "MARKET_VALUE"
VALUATION_METHOD_FAIR_VALUE = "FAIR_VALUE"
VALUATION_METHOD_BOOK_VALUE = "BOOK_VALUE"
VALUATION_METHOD_COST = "COST"
VALUATION_METHOD_NONE = "NONE"

VALUATION_METHODS = {
    VALUATION_METHOD_DCF,
    VALUATION_METHOD_MARKET_VALUE,
    VALUATION_METHOD_FAIR_VALUE,
    VALUATION_METHOD_BOOK_VALUE,
    VALUATION_METHOD_COST,
    VALUATION_METHOD_NONE,
}

# ==========================================================
# 3. Classification Status Taxonomy
# ==========================================================
CLASSIFICATION_STATUS_COMPLETE = "COMPLETE"
CLASSIFICATION_STATUS_PARTIAL = "PARTIAL"
CLASSIFICATION_STATUS_UNRESOLVED = "UNRESOLVED"
CLASSIFICATION_STATUS_CONFLICTING = "CONFLICTING"

CLASSIFICATION_STATUSES = {
    CLASSIFICATION_STATUS_COMPLETE,
    CLASSIFICATION_STATUS_PARTIAL,
    CLASSIFICATION_STATUS_UNRESOLVED,
    CLASSIFICATION_STATUS_CONFLICTING,
}
